# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[pt]
  languageCode = "pt-brasil"
  contentDir = "content/pt"
  title = "Maxwel Coura Oliveira"
  [pt.params]
    description = "Site description in Chinese..."
  
[[pt.menu.main]]
  name = "Sobre"
  url = "#about"
  weight = 10

[[pt.menu.main]]
  name = "Blog"
  url = "#posts"
  weight = 20

[[pt.menu.main]]
  name = "Projetos"
  url = "#projects"
  weight = 30

#[[pt.menu.main]]
#  name = "Publicações"
#  url = "#publications"
#  weight = 40

#[[pt.menu.main]]
#  name = "Cursos"
#  url = "courses/"
#  weight = 50

[[pt.menu.main]]
  name = "Contato"
  url = "#contact"
  weight = 60

